# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x08ruche.v1\"\xe9\x01\n\x0b\x43hatRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x02 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\t\x12\x17\n\x0fuser_channel_id\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\x12\x12\n\nsession_id\x18\x06 \x01(\t\x12\x35\n\x08metadata\x18\x07 \x03(\x0b\x32#.ruche.v1.ChatRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xc6\x01\n\x0c\x43hatResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x0f\n\x07turn_id\x18\x03 \x01(\t\x12)\n\x08scenario\x18\x04 \x01(\x0b\x32\x17.ruche.v1.ScenarioState\x12\x15\n\rmatched_rules\x18\x05 \x03(\t\x12\x14\n\x0ctools_called\x18\x06 \x03(\t\x12\x13\n\x0btokens_used\x18\x07 \x01(\x05\x12\x12\n\nlatency_ms\x18\x08 \x01(\x05\")\n\rScenarioState\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\t\"t\n\tChatChunk\x12\x0f\n\x05token\x18\x01 \x01(\tH\x00\x12&\n\x04\x64one\x18\x02 \x01(\x0b\x32\x16.ruche.v1.ChatResponseH\x00\x12%\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x14.ruche.v1.ErrorEventH\x00\x42\x07\n\x05\x63hunk\"+\n\nErrorEvent\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x8e\x01\n\x0b\x43hatService\x12<\n\x0bSendMessage\x12\x15.ruche.v1.ChatRequest\x1a\x16.ruche.v1.ChatResponse\x12\x41\n\x11SendMessageStream\x12\x15.ruche.v1.ChatRequest\x1a\x13.ruche.v1.ChatChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_CHATREQUEST']._serialized_start=25
  _globals['_CHATREQUEST']._serialized_end=258
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_start=211
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_end=258
  _globals['_CHATRESPONSE']._serialized_start=261
  _globals['_CHATRESPONSE']._serialized_end=459
  _globals['_SCENARIOSTATE']._serialized_start=461
  _globals['_SCENARIOSTATE']._serialized_end=502
  _globals['_CHATCHUNK']._serialized_start=504
  _globals['_CHATCHUNK']._serialized_end=620
  _globals['_ERROREVENT']._serialized_start=622
  _globals['_ERROREVENT']._serialized_end=665
  _globals['_CHATSERVICE']._serialized_start=668
  _globals['_CHATSERVICE']._serialized_end=810
# @@protoc_insertion_point(module_scope)
