# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ruche.api.grpc import config_pb2 as config__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigServiceStub(object):
    """ConfigService provides configuration management operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListRules = channel.unary_unary(
                '/ruche.v1.ConfigService/ListRules',
                request_serializer=config__pb2.ListRulesRequest.SerializeToString,
                response_deserializer=config__pb2.ListRulesResponse.FromString,
                _registered_method=True)
        self.CreateRule = channel.unary_unary(
                '/ruche.v1.ConfigService/CreateRule',
                request_serializer=config__pb2.CreateRuleRequest.SerializeToString,
                response_deserializer=config__pb2.Rule.FromString,
                _registered_method=True)
        self.ListScenarios = channel.unary_unary(
                '/ruche.v1.ConfigService/ListScenarios',
                request_serializer=config__pb2.ListScenariosRequest.SerializeToString,
                response_deserializer=config__pb2.ListScenariosResponse.FromString,
                _registered_method=True)
        self.CreateScenario = channel.unary_unary(
                '/ruche.v1.ConfigService/CreateScenario',
                request_serializer=config__pb2.CreateScenarioRequest.SerializeToString,
                response_deserializer=config__pb2.Scenario.FromString,
                _registered_method=True)


class ConfigServiceServicer(object):
    """ConfigService provides configuration management operations
    """

    def ListRules(self, request, context):
        """List rules for an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRule(self, request, context):
        """Create a new rule
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListScenarios(self, request, context):
        """List scenarios for an agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateScenario(self, request, context):
        """Create a new scenario
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListRules': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRules,
                    request_deserializer=config__pb2.ListRulesRequest.FromString,
                    response_serializer=config__pb2.ListRulesResponse.SerializeToString,
            ),
            'CreateRule': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRule,
                    request_deserializer=config__pb2.CreateRuleRequest.FromString,
                    response_serializer=config__pb2.Rule.SerializeToString,
            ),
            'ListScenarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListScenarios,
                    request_deserializer=config__pb2.ListScenariosRequest.FromString,
                    response_serializer=config__pb2.ListScenariosResponse.SerializeToString,
            ),
            'CreateScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateScenario,
                    request_deserializer=config__pb2.CreateScenarioRequest.FromString,
                    response_serializer=config__pb2.Scenario.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ruche.v1.ConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ruche.v1.ConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService(object):
    """ConfigService provides configuration management operations
    """

    @staticmethod
    def ListRules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ruche.v1.ConfigService/ListRules',
            config__pb2.ListRulesRequest.SerializeToString,
            config__pb2.ListRulesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ruche.v1.ConfigService/CreateRule',
            config__pb2.CreateRuleRequest.SerializeToString,
            config__pb2.Rule.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListScenarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ruche.v1.ConfigService/ListScenarios',
            config__pb2.ListScenariosRequest.SerializeToString,
            config__pb2.ListScenariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ruche.v1.ConfigService/CreateScenario',
            config__pb2.CreateScenarioRequest.SerializeToString,
            config__pb2.Scenario.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
