# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from ruche.api.grpc import memory_pb2 as memory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub(object):
    """MemoryService provides memory management operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddEpisode = channel.unary_unary(
                '/ruche.v1.MemoryService/AddEpisode',
                request_serializer=memory__pb2.AddEpisodeRequest.SerializeToString,
                response_deserializer=memory__pb2.AddEpisodeResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/ruche.v1.MemoryService/Search',
                request_serializer=memory__pb2.SearchRequest.SerializeToString,
                response_deserializer=memory__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.GetEntity = channel.unary_unary(
                '/ruche.v1.MemoryService/GetEntity',
                request_serializer=memory__pb2.GetEntityRequest.SerializeToString,
                response_deserializer=memory__pb2.Entity.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """MemoryService provides memory management operations
    """

    def AddEpisode(self, request, context):
        """Add a new episode to memory
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search memory using semantic or keyword search
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntity(self, request, context):
        """Get a specific entity by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.AddEpisode,
                    request_deserializer=memory__pb2.AddEpisodeRequest.FromString,
                    response_serializer=memory__pb2.AddEpisodeResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=memory__pb2.SearchRequest.FromString,
                    response_serializer=memory__pb2.SearchResponse.SerializeToString,
            ),
            'GetEntity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntity,
                    request_deserializer=memory__pb2.GetEntityRequest.FromString,
                    response_serializer=memory__pb2.Entity.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ruche.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ruche.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """MemoryService provides memory management operations
    """

    @staticmethod
    def AddEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ruche.v1.MemoryService/AddEpisode',
            memory__pb2.AddEpisodeRequest.SerializeToString,
            memory__pb2.AddEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ruche.v1.MemoryService/Search',
            memory__pb2.SearchRequest.SerializeToString,
            memory__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ruche.v1.MemoryService/GetEntity',
            memory__pb2.GetEntityRequest.SerializeToString,
            memory__pb2.Entity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
