"""Add lineage and status columns to profile_assets.

Revision ID: 009
Revises: 008
Create Date: 2025-12-03

Adds:
- status: active/superseded/expired/orphaned
- source_item_id: for lineage tracking
- source_item_type: type of source item
- derived_from_tool: tool ID if asset was generated by tool
- superseded_by_id: link to replacing asset
- superseded_at: when superseded
- analysis_field_ids: fields derived from this asset
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ARRAY, UUID

revision = "009"
down_revision = "008"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Add lineage and status columns to profile_assets."""
    # Add status column with default 'active'
    op.add_column(
        "profile_assets",
        sa.Column(
            "status",
            sa.String(20),
            server_default="active",
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "chk_asset_status",
        "profile_assets",
        "status IN ('active', 'superseded', 'expired', 'orphaned')",
    )

    # Lineage columns
    op.add_column(
        "profile_assets",
        sa.Column("source_item_id", UUID, nullable=True),
    )
    op.add_column(
        "profile_assets",
        sa.Column("source_item_type", sa.String(50), nullable=True),
    )
    op.add_column(
        "profile_assets",
        sa.Column("derived_from_tool", sa.String(255), nullable=True),
    )

    # Supersession columns
    op.add_column(
        "profile_assets",
        sa.Column(
            "superseded_by_id",
            UUID,
            sa.ForeignKey("profile_assets.id"),
            nullable=True,
        ),
    )
    op.add_column(
        "profile_assets",
        sa.Column("superseded_at", sa.TIMESTAMP(timezone=True), nullable=True),
    )

    # Analysis tracking - which fields were derived from this asset
    op.add_column(
        "profile_assets",
        sa.Column("analysis_field_ids", ARRAY(UUID), server_default="{}", nullable=False),
    )

    # Indexes for efficient queries
    op.create_index(
        "idx_profile_assets_status",
        "profile_assets",
        ["tenant_id", "profile_id", "status"],
    )
    op.create_index(
        "idx_profile_assets_source_item",
        "profile_assets",
        ["source_item_id"],
        postgresql_where=sa.text("source_item_id IS NOT NULL"),
    )


def downgrade() -> None:
    """Remove lineage and status columns from profile_assets."""
    # Drop indexes
    op.drop_index("idx_profile_assets_source_item")
    op.drop_index("idx_profile_assets_status")

    # Drop columns
    op.drop_column("profile_assets", "analysis_field_ids")
    op.drop_column("profile_assets", "superseded_at")
    op.drop_column("profile_assets", "superseded_by_id")
    op.drop_column("profile_assets", "derived_from_tool")
    op.drop_column("profile_assets", "source_item_type")
    op.drop_column("profile_assets", "source_item_id")

    # Drop status constraint and column
    op.drop_constraint("chk_asset_status", "profile_assets", type_="check")
    op.drop_column("profile_assets", "status")
