"""ASA validation and suggestion models.

This module defines the core data models used by the Agent Setter Agent (ASA)
for validation results, issues, suggestions, and policy recommendations.
"""

from enum import Enum
from pydantic import BaseModel, Field


class Severity(str, Enum):
    """Severity level for validation issues."""

    ERROR = "error"  # Blocks deployment
    WARNING = "warning"  # Should be reviewed but doesn't block
    INFO = "info"  # Informational, no action required


class Issue(BaseModel):
    """A validation issue found during configuration validation."""

    severity: Severity
    code: str = Field(..., description="Machine-readable error code")
    message: str = Field(..., description="Human-readable description")
    fix: str | None = Field(None, description="Suggested fix for the issue")
    location: str | None = Field(None, description="Where the issue was found (e.g., tool name, step name)")


class Suggestion(BaseModel):
    """A suggestion for improving configuration."""

    code: str = Field(..., description="Machine-readable suggestion code")
    message: str = Field(..., description="Human-readable suggestion")
    recommended_change: dict | None = Field(None, description="Recommended configuration change")
    details: dict | None = Field(None, description="Additional details about the suggestion")


class ValidationResult(BaseModel):
    """Result of validating a configuration artifact."""

    valid: bool = Field(..., description="Whether the configuration is valid")
    issues: list[Issue] = Field(default_factory=list, description="Validation issues found")
    suggestions: list[Suggestion] = Field(default_factory=list, description="Suggestions for improvement")

    @property
    def errors(self) -> list[Issue]:
        """Get only ERROR severity issues."""
        return [i for i in self.issues if i.severity == Severity.ERROR]

    @property
    def warnings(self) -> list[Issue]:
        """Get only WARNING severity issues."""
        return [i for i in self.issues if i.severity == Severity.WARNING]

    @property
    def has_errors(self) -> bool:
        """Check if there are any blocking errors."""
        return len(self.errors) > 0


class SideEffectPolicy(str, Enum):
    """Side-effect policy for tool execution (alignment mechanic specific)."""

    PURE = "pure"  # No side effects
    IDEMPOTENT = "idempotent"  # Can be retried safely
    COMPENSATABLE = "compensatable"  # Has a compensation action
    IRREVERSIBLE = "irreversible"  # Cannot be undone


class PolicySuggestion(BaseModel):
    """Suggested side-effect policy for a tool."""

    suggested_policy: SideEffectPolicy
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score 0-1")
    reasoning: str = Field(..., description="Human-readable explanation")
    alternatives: list[SideEffectPolicy] = Field(
        default_factory=list,
        description="Alternative policies to consider",
    )


class SuggestedRule(BaseModel):
    """A suggested rule generated by edge case analysis."""

    name: str
    description: str
    trigger_condition: str
    trigger_scope: str | None = None
    suggested_action: str
    priority: int = 50
    auto_generated: bool = True


class DeploymentValidationResult(BaseModel):
    """Result of validating all configurations before deployment."""

    can_deploy: bool = Field(..., description="Whether deployment should proceed")
    errors: list[Issue] = Field(default_factory=list, description="Blocking errors")
    warnings: list[Issue] = Field(default_factory=list, description="Warnings that don't block deployment")
    suggestions: list[Suggestion] = Field(default_factory=list, description="Improvement suggestions")


class ConfigSchema(BaseModel):
    """Configuration schema for a cognitive mechanic."""

    artifacts: list["ArtifactSchema"] = Field(
        default_factory=list,
        description="Configuration artifacts required by this mechanic",
    )
    parameters: list["ParameterSchema"] = Field(
        default_factory=list,
        description="Configuration parameters for this mechanic",
    )


class ArtifactSchema(BaseModel):
    """Schema for a configuration artifact."""

    name: str
    type: str  # e.g., "graph", "list", "dict", "string", "vector_store"
    required: bool = True
    description: str | None = None


class ParameterSchema(BaseModel):
    """Schema for a configuration parameter."""

    name: str
    type: str  # e.g., "enum", "int", "float", "bool", "string"
    required: bool = True
    description: str | None = None
    default: str | int | float | bool | None = None
    # Type-specific constraints
    values: list[str] | None = None  # For enum types
    min: int | float | None = None  # For numeric types
    max: int | float | None = None  # For numeric types
